[[buildpacks]]
id = "org.toolforge.buildpacks.python39"
version = "0.0.3"
uri = "./python39"

[[buildpacks]]
id = "org.toolforge.buildpacks.pip"
version = "0.0.3"
uri = "./pip"

[[buildpacks]]
id = "org.toolforge.buildpacks.uwsgi"
version = "0.0.3"
uri = "./uwsgi"

[[order]]
[[order.group]]
id = "org.toolforge.buildpacks.python39"
version = "0.0.3"
optional = true

[[order.group]]
id = "org.toolforge.buildpacks.pip"
version = "0.0.3"
optional = true

[[order.group]]
id = "org.toolforge.buildpacks.uwsgi"
version = "0.0.3"

[stack]
id = "org.toolforge.buildpacks.stack.bullseye0"
run-image = "docker-registry.tools.wmflabs.org/toolforge-bullseye0-run:latest"
build-image = "docker-registry.tools.wmflabs.org/toolforge-bullseye0-build:latest"
